### ISSUE TITLE
ExpressionToSql<T>.Select(t => t)   would  raise stackoverflow execption

### ISSUE THREAD

**Issue by jello-chen** [StrangeCity/Expression2Sql#2]
In cnblogs,I take the introduction of the repo.

**Comment by StrangeCity** [comment]
Hi jello:
         thank you for your feedback,now repaired.

**Comment by jello-chen** [comment]
I executed git clone again,It raise the ArgumentException you throw about "cannot parse the expression".

**Comment by StrangeCity** [comment]
not support ExpressionToSql<T>.Select(t => t)
you can try ExpressionToSql<T>.Select()
